name: "Test Pre Commit Action"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-pre-commit-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7

        # TODO: After it passes the check change it
      - name: Test Pre Commit Action
        uses: thedevmystic/mystic-github-actions/pre-commit@main
